title: Fatih S. Sarikurt
description: >-
  Principal Engineer with a Ph.D. in Nuclear Engineering. Expertise in nuclear reactor design,
  high-fidelity CFD applications, multiphysics, and multiscale modeling of nuclear reactor systems.
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Fatih S. Sarikurt, Ph.D."
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Principal Engineer with a Ph.D. in Nuclear Engineering. Expertise in nuclear reactor design, high-fidelity CFD applications, multiphysics, and multiscale modeling of nuclear reactor systems."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fatih-sinan-sarikurt"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=vaZyCtIAAAAJ&hl"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fatih-sinan-sarikurt"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=vaZyCtIAAAAJ&hl"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/